FROM node:20.19.4-bookworm-slim

ENV NODE_ENV=production
WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends postgresql-client bash tini ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .
RUN chmod +x /usr/src/app/entrypoint.sh

ENTRYPOINT ["/usr/bin/tini","--"]
CMD ["/usr/src/app/entrypoint.sh"]
