name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint-and-i18n:
    name: Lint and i18n audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.4'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run ESLint UI guard
        run: npm run lint

      - name: Verify translation coverage
        run: npm run i18n:audit
